# .streamlit/secrets.toml

[connections.snowflake]
account = "DBBSBED-PLB63968"
user = "good0430"
password = "kasdfasdlj@#d2141D!"
role = "sysadmin"
warehouse = "compute_wh"
database = "smoothies"
schema = "public"
client_session_keep_alive = true
